# See doc/docker/README.md or https://github.com/instructure/canvas-lms/tree/master/doc/docker
services:
  web: &WEB
    build:
      context: .
    links:
      - postgres
      - redis
    environment:
      POSTGRES_PASSWORD: sekret
    volumes:
      - .:/usr/src/app

  jobs:
    <<: *WEB
    command: bundle exec script/delayed_job run

  postgres:
    build: ./docker-compose/postgres
    environment:
      POSTGRES_PASSWORD: sekret
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
